#!/bin/bash

# Run this file if you got the source from a git repository.
# Running this generate some GNU autotools files that will complete the
# tarball source of this package.

set -ex

cd $(dirname ${BASH_SOURCE[0]})


for f in NEWS README AUTHORS ChangeLog COPYING ; do
    if [ ! -e $f ] ; then
        touch $f
    fi
done

autoreconf --force --verbose --install

