#!/bin/bash

# Run this file if you got the source from a git repository.
# Running this generates some GNU autotools files that will complete the
# tarball source of this package.  A bootstrap script is required to
# using GNU autotools.   A bootstrap 

set -ex

cd $(dirname ${BASH_SOURCE[0]})


for f in NEWS README AUTHORS ChangeLog COPYING ; do
    if [ ! -e $f ] ; then
        touch $f
    fi
done

./RELEASE.bash configure.ac.in > configure.ac

autoreconf --force --verbose --install

