#!/bin/bash

# This file was part of the quickbuild software package.
# 
# quickbuild is free software that is distributed under the free software
# foundation's GNU Affero General Public License (AGPL) version 3.
#
# For more information see the quickbuild package homepage at:
#   https://github.com/lanceman2/quickbuild
#
# You can get the latest version of this file from:
# 
#  https://raw.githubusercontent.com/lanceman2/quickbuild/master/examples/bootstrap_download/bootstrap
#
##############################################################################


# The tag can be "master" or a full git check-in hash in lower case hex
# like for example:
#tag=dc184319be9a272ffa4528f5bb5d0902f1edbbbb
tag=0.2
url=https://raw.githubusercontent.com/lanceman2/quickbuild/$tag/quickbuild.make

# If we wanted a particular file, so we checks it's sha512 sum.
# Run:
#
#    sha512sum quickbuild.make
#
# to get this long hex number

sha512sum=d72c983ea6e308312be9b2e2503c754840c98b7d78\
f3b37c64c45d84fc844e0b4773e33ad3addf8267d84ccc626ae0\
afb41530f46769f6584da279c7fd4519e3


function usage()
{
    cat <<EOF

  Usage: $0

  This script downloads and compresses a make file
  from the web via url:

     $url


EOF
    exit 1
}


[ "$1" = "--help" ] && usage
[ "$1" = "-h" ] && usage

set -ex

# Go to the directory there this script is.
cd $(dirname ${BASH_SOURCE[0]})


./RELEASE.bash package.make.rl > package.make
./RELEASE.bash config.make.example.rl > config.make.example

[ -e config.make ] || cp config.make.example config.make



if [ -z "$*" ] && [ -e quickbuild.make ] ; then
    set +x
    cat <<EOF

  The file quickbuild.make exists.

EOF
    exit
fi


############################################################
# The rest of this script is for creating quickbuild.make
############################################################


set -e
cat <<EOF > quickbuild.make.tmp
# This is a generated file
#
#  You can get the uncompressed and better commented original version
#  of this file from:
#
#      $url
#

EOF


# get the quickbuild.make file from the web
# --no-check-certificate will make this succeed even if certificates are
# not cool, but we have a sha512sum so that it's fine.
wget --no-check-certificate $url -O quickbuild.make.org 

if [ -n "$sha512sum" ] ; then
    set +x
    # We wanted a particular file, so we checks it's sha512 sum.
    echo "$sha512sum  quickbuild.make.org" | sha512sum -c
    set -x
else
    set +x
    echo "The sha512sum of the downloaded file, before compressing it:"
    set -x
    sha512sum quickbuild.make.org
fi

sed quickbuild.make.org -e 's/^\s*\#.*$//g' -e '/^$/d' >> quickbuild.make.tmp

rm quickbuild.make.org
mv quickbuild.make.tmp quickbuild.make

set +x

cat <<EOF


  Edit: config.make to change your installation PREFIX


  Then: run 'make'


EOF


