#!/bin/bash

set -eo pipefail

in=$0.IN.tmp
out=$0.OUT.tmp

# dd count blocks  1 block = 512bytes

#dd if=/dev/urandom count=30 | hexdump > $in


# This will call the tests/copy input() function lots more than all other
# input() functions, checking the buffer advancement for the extreme case
# with a single byte input() at a time.
#

set -x
../bin/quickstream -f tests/count\
 -f tests/countCheck [ --maxRead 24 ]\
 -c -R -r > /dev/null


set +x
echo -e "\n                  $0 SUCCESS\n"

exit

../bin/quickstream -f tests/count\
 -f tests/countCheck\
 -f stdout -c -R -r > /dev/null




../bin/quickstream -f stdin\
 -f tests/copy [ --maxRead=7 ]\
 -f stdout -c -R -d -r < $in > $out


