#!/bin/bash

set -eo pipefail

in=$0.IN.tmp
out=$0.OUT.tmp

# dd count blocks  1 block = 512bytes

#dd if=/dev/urandom count=3 | hexdump > $in



../bin/quickstream\
 -f tests/sequenceGen { --length 10200 }\
 -f tests/passThrough\
 -f tests/passThrough { --sleep 1 }\
 -f tests/copy\
 -f tests/passThrough\
 -f tests/sequenceCheck { --maxWrite 10 }\
 -c\
 -t 7\
 -R -r


#du -sb $in $out

#diff -q $in $out

echo "SUCCESS"

exit

