#!/bin/bash

set -e

source testsEnv


in=$0.IN.tmp
out=$0.OUT.tmp

# dd count blocks  1 block = 512bytes

dd if=/dev/urandom count=1300 of=$in

$QS_RUN -f stdin -f stdout -c -t 3 -r < $in > $out

diff $in $out
echo "$0 SUCCESS"
