#!/bin/bash

set -e

source testsEnv

in=$0.IN.tmp
out=$0.OUT.tmp

# dd count blocks  1 block = 512bytes

#dd if=/dev/urandom count=133 of=$in
dd if=/dev/urandom count=30 2> /dev/null | hexdump > $in 


# This will call the tests/copy input() function lots more than all other
# input() functions, checking the buffer advancement for the extreme case
# with a single byte input() at a time.
#

$QS_RUN\
 -v 4 -f stdin\
 -f tests/copy\
 -f tests/copy\
 -f tests/copy\
 -f stdout -c -r < $in > $out

diff -q $in $out
echo "$0 SUCCESS"
