#!/bin/bash

set -e

source testsEnv

$QS_RUN\
 -v 2\
 -f tests/sequenceGen { --length 102001 }\
 -f tests/passThrough\
 -f tests/sequenceCheck { --maxWrite 10 }\
 -p "0 1 0 0"\
 -p "0 1 1 1"\
 -p "1 2 0 0"\
 -p "1 2 1 1"\
 -r

echo "SUCCESS"
