#!/bin/bash

set -e

source testsEnv

../bin/quickstream\
 -v 3\
 -f tests/sequenceGen { --length 109332 }\
 -f tests/passThrough\
 -f tests/passThrough\
 -f tests/passThrough\
 -f tests/passThrough\
 -f tests/passThrough\
 -f tests/sequenceCheck { --maxWrite 10 }\
 -c\
 -r -r -r -r -r -r

echo "SUCCESS"
