#!/bin/bash

set -e

in=$0.IN.tmp
out=$0.OUT.tmp

# dd count blocks  1 block = 512bytes

dd if=/dev/urandom count=1300 of=$in


QS_MODULE_PATH=.\
 ../bin/quickstream\
 -f stdin\
 -f my_stdout\
 -c -t 1 -r < $in > $out

du -hb $in $out
diff $in $out
echo "$0 SUCCESS"
