#!/bin/bash

set -xe

source testsEnv

in=$0.IN.tmp
out=$0.OUT.tmp

# dd count blocks  1 block = 512bytes

dd if=/dev/urandom count=1300 of=$in

# A complex flow graph with 2 very different streams.
$QS_RUN\
 -v 3\
 -f tests/sequenceGen { --length 302000 }\
 -f tests/sequenceCheck { --maxWrite=1001 }\
 -f tests/sequenceCheck { --seedStart 1 --maxWrite=13 }\
 -f tests/sequenceCheck { --maxWrite=30 }\
 -f tests/sequenceCheck { --seedStart 1 --maxWrite=30 }\
 -f tests/sequenceCheck { --seedStart 1 --maxWrite=300 --seeds "1" }\
 -f tests/sequenceCheck { --maxWrite=3034 }\
 -f tests/sequenceCheck { --maxWrite=302 --seeds "1 0 0 1" }\
 -t 6\
 -p "0 1 0 0"\
 -p "0 2 1 0"\
 -p "1 3 0 0"\
 -p "2 4 0 0"\
 -p "2 5 0 0"\
 -p "3 6 0 0"\
 -p "5 6 0 1"\
 -p "5 7 0 0"\
 -p "0 7 0 1"\
 -p "3 7 0 2"\
 -p "4 7 0 3"\
 -s\
 -f stdin\
 -f tests/copy\
 -f stdout\
 -c\
 -r < $in > $out

diff $in $out

set +x

echo "$0 SUCCESS"
