#!/bin/bash

set -e

source testsEnv

compare=$0.compare
out=$(basename $0).OUT.tmp


set -x
echo "Hello123" | ../bin/quickstream -C tests/dummy -f stdin -f stdout -c -t 1 -r > $out

diff $compare $out
set +x
echo "$0 SUCCESS"
