#!/bin/bash

set -e

source testsEnv


set -x
../bin/quickstream\
 -C tests/parameter\
 -f tests/sequenceGen.so { --name seq --maxWrite 128 --length 1000 }\
 -f stdout\
 -c -t 0 -r

set +x
echo "$0 SUCCESS"
