#!/bin/bash

set -e

source testsEnv


set -x
../bin/quickstream -v 3\
 -C bytesCounter\
 -C tests/byteMonitor\
 -f tests/sequenceGen.so {\
 --maxWrite 1000\
 --length 500300 }\
 -f tests/sequenceCheck\
 -f tests/sequenceCheck\
 -c -t 1 -r


set +x
echo "$0 SUCCESS"
