#!/bin/bash

set -e

source testsEnv

$QS_RUN\
 -v 2\
 -f tests/sequenceGen { --length 10000 --maxWrite=3 }\
 -f tests/sequenceCheck { --maxWrite=1001 }\
 -f tests/sequenceCheck { --maxWrite=13 }\
 -f tests/sequenceCheck { --maxWrite=30 }\
 -t 4\
 -c\
 -R -r

echo "$0 SUCCESS"
