#!/bin/bash

set -e

source testsEnv

../bin/quickstream\
 -v 2\
 -f tests/sequenceGen { --length 1000 }\
 -f tests/sequenceCheck { --maxWrite=1001 }\
 -f tests/sequenceCheck { --seedStart 1 --maxWrite=13 }\
 -f tests/sequenceCheck { --maxWrite=30 }\
 -f tests/sequenceCheck { --seedStart 1 --maxWrite=13 }\
 -t 2\
 -p "0 1 0 0"\
 -p "0 2 1 0"\
 -p "1 3 0 0"\
 -p "2 4 0 0"\
 -R -r

echo "$0 SUCCESS"
