#!/bin/bash

set -e

source testsEnv

$QS_RUN\
 -v 4\
 -f tests/sequenceGen { --length 100000 }\
 -f tests/sequenceCheck { --maxWrite=1001 }\
 -f tests/sequenceCheck { --seedStart 1 --maxWrite=13 }\
 -f tests/sequenceCheck { --maxWrite=30 }\
 -f tests/sequenceCheck { --seedStart 1 --maxWrite=30 }\
 -f tests/sequenceCheck { --seedStart 1 --maxWrite=300 }\
 -f tests/sequenceCheck { --maxWrite=3034 }\
 -t 9\
 -p "0 1 0 0"\
 -p "0 2 1 0"\
 -p "1 3 0 0"\
 -p "2 4 0 0"\
 -p "2 5 0 0"\
 -p "3 6 0 0"\
 -p "5 6 0 1"\
 -R\
 -r

echo "$0 SUCCESS"
