#!/bin/bash

set -e

source testsEnv


set -x
$QS_RUN -v 5\
 -C bytesCounter { --report-period 0.03 }\
 -C bytesRate\
 -C tests/hello { --foo bar }\
 -C tests/hello.py { --name hellO --call 88 }\
 -f tests/sequenceGen.so {\
 --maxWrite 1000\
 --length 80003 }\
 -f tests/sequenceCheck\
 -f tests/sequenceCheck\
 -c -t 0 -r


set +x
echo "$0 SUCCESS"
