#!/bin/bash

set -e

source testsEnv


set -x
$QS_RUN -v 3\
 -C bytesCounter { --report-period 0.03 }\
 -C bytesRate\
 -C pythonMonitor.py\
 -f tests/sequenceGen.so {\
 --maxWrite 1000\
 --length 80003 }\
 -f tests/sequenceCheck\
 -f tests/sequenceCheck\
 -c -t 0 -r


set +x
echo "$0 SUCCESS"
