
INSTALL_DIR = $(PREFIX)/lib/quickstream/plugins/filters/tests

sleep.so_SOURCES := sleep.c
copy.so_SOURCES := copy.c
outFile.so_SOURCES := outFile.c
count.so_SOURCES = count.c
countCheck.so_SOURCES = countCheck.c


include ../../../../../quickbuild.make
