SUBDIRS := tests

INSTALL_DIR = $(PREFIX)/lib/quickstream/plugins/filters

stdin.so_SOURCES := stdin.c
stdout.so_SOURCES := stdout.c
rtl_sdr_rx.so_SOURCES := rtl_sdr_rx.c


include ../../../../quickbuild.make
