SUBDIRS := tests

INSTALL_DIR = $(PREFIX)/lib/quickstream/plugins/controllers

#rtl_sdr_rx.so_SOURCES := rtl_sdr_rx.c


bytesCounter.so_SOURCES := bytesCounter.c


include ../../../../quickbuild.make
