
INSTALL_DIR = $(PREFIX)/include

INSTALLED := qsfilter.h qsapp.h

# Tell quickbuild that PACKAGE_VERSION is a string that is sed substituted
# in @PACKAGE_VERSION@ in *.in files like qsapp.h.in
#
IN_VARS := PACKAGE_VERSION



include ../quickbuild.make
