#!/bin/bash

set -e

in=$0.IN.tmp
out=$0.OUT.tmp

# dd count blocks  1 block = 512bytes

dd if=/dev/urandom count=10 of=$in

../../bin/quickstream -f stdin -f stdout -c -R -d -r < $in > $out

diff $in $out

echo "SUCCESS"
