#!/bin/bash

set -e


# A complex flow graph being run by one thread.
../../bin/quickstream\
 -f tests/sequenceGen [ --length 102000 ]\
 -f tests/sequenceCheck [ --maxWrite=8001 ]\
 -f tests/sequenceCheck [ --seedStart 1 --maxWrite=13 ]\
 -f tests/sequenceCheck [ --maxWrite=30 ]\
 -f tests/sequenceCheck [ --seedStart 1 --maxWrite=30 ]\
 -f tests/sequenceCheck [ --seedStart 1 --maxWrite=300 --seeds "1" ]\
 -f tests/sequenceCheck [ --maxWrite=8034 ]\
 -f tests/sequenceCheck [ --maxWrite=302 --seeds "1 0 0 1" ]\
 -t 1\
 -p "0 1 0 0"\
 -p "0 2 1 0"\
 -p "1 3 0 0"\
 -p "2 4 0 0"\
 -p "2 5 0 0"\
 -p "3 6 0 0"\
 -p "5 6 0 1"\
 -p "5 7 0 0"\
 -p "0 7 0 1"\
 -p "3 7 0 2"\
 -p "4 7 0 3"\
 -R\
 -d -r

echo "$0 SUCCESS"
