
INSTALL_DIR = $(PREFIX)/include/quickstream

INSTALLED := filter.h app.h

# Tell quickbuild that PACKAGE_VERSION is a string that is sed substituted
# in @PACKAGE_VERSION@ in *.in files like app.h.in
#
IN_VARS := PACKAGE_VERSION



include ../quickbuild.make
